### ISSUE TITLE
Also include glyph colors palettes?

### ISSUE THREAD

**Issue by LettError** [connordavenport/Theme-Manager#1]
(lazy feature request)

**Comment by frankrolf** [comment]
<img width="146" alt="Screen Shot 2019-08-15 at 12 59 23" src="https://user-images.githubusercontent.com/2049645/63090742-86255200-bf5c-11e9-8e95-8e3cd1786859.png">

https://gist.github.com/frankrolf/9d7fc229710dbf31b7c078e06159812b

**Comment by connordavenport** [comment]
oOo0 this is great, @frankrolf . Thanks for sharing. 
@LettError sorry that I am just getting around to this, I like this idea!. I will work on adding the color palette to the themes. I just need to decide if we overwrite the existing or append to (which might get a bit messy but won't delete the users original colors).
