### ISSUE TITLE
Point coordinates can't be light on a dark background (they disappear or are covered by black)

### ISSUE THREAD

**Issue by arrowtype** [connordavenport/Theme-Manager#6]
I have a WIP dark theme, but I've come across a problem: point coordinate values are very difficult to read.

Unfortunately, even when I try changing their color to something like yellow or magenta, they appear to have that color but also be covered in black:

![image](https://user-images.githubusercontent.com/45946693/75637319-afa18480-5bf3-11ea-8bc8-09eed1787165.png)

Worse, if I go to white or almost white, it completely fades away, as if the blend mode were "multiply" or something:

![image](https://user-images.githubusercontent.com/45946693/75637374-1161ee80-5bf4-11ea-9628-81aed0df26dd.png)

My guess is, this might be a RoboFont issue. Is there a good way to find out?

**Comment by connordavenport** [comment]
Hey Stephen, sorry for the late reply. This is most likely a RoboFont issue — if you edit the value in the preference panel does the issue still persist?

**Comment by arrowtype** [comment]
Good test, thanks! Yes, the issue did persist. I’ve made a post over on the RoboFont Forum:

https://forum.robofont.com/topic/855/point-coordinate-color-not-possible-as-reverse-color-light-on-dark-background
